name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    
      - dependabot/** # Gatilho para PRs do Dependabot
  workflow_dispatch: # Permite executar o pipeline manualmente

jobs:
  test:
    runs-on: ubuntu-latest # Máquina virtual para rodar os testes

    steps:
      # Etapa 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Etapa 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' #

      # Etapa 3: Instalar dependências do projeto
      - name: Install dependencies
        run: npm install
      
      # Etapa 4: Executar testes Cypress
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/taskapp/*"

      # Etapa 5: Configurar conexão com MongoDB local e rodar os testes
      - name: Run tests with local MongoDB
        run: |
          echo "Setting up MongoDB URI..."
          export MONGO_URI=mongodb://localhost:27017/taskapp  # Configuração local para MongoDB
          echo "Running tests with local MongoDB..."
          npm run test-api  # Comando para rodar os testes no código do projeto
        env:
          NODE_ENV: test  # Ambiente de testes
          MONGO_URI: mongodb://localhost:27017/taskapp  # URI local do MongoDB

      # Etapa 6: Confirmar se o servidor local está acessível antes de rodar os testes
      - name: Confirm local server connection
        run: |
          echo "Checking connection to local server..."
          curl -I http://localhost:8081 || exit 1  # Verificar se o servidor local está acessível
        env:
          SERVER_URL: http://localhost:8081  # URL do servidor local

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":true}' \
            https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deploys
