name: CI/CD Pipeline

on:
  push:
    branches:
      - coisa-nova
  pull_request:
    branches:
      - main    
      - dependabot/** # Gatilho para PRs do Dependabot
  workflow_dispatch: # Permite executar o pipeline manualmente

jobs:
  test:
    runs-on: ubuntu-24.04

    env: # Configuração global para todas as etapas do job
      MONGO_URI_PROD: ${{ secrets.MONGO_URI_PROD }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODE_ENV: production 

    steps:
      # Etapa 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Etapa 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'

      
        
        
      # # Etapa 3: Instalar dependências do projeto
      # - name: Install dependencies
      #   run: npm install

      - name: Remove node_modules
        run: rm -rf node_modules
      # **Etapa 4: Instalar Cypress**
      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Debug Installation
        run: |
          npm list cypress
          ls node_modules/cypress || echo "Cypress not found"
          cat package.json
      

      # Etapa 4: Iniciar servidor local
      - name: Start local server
        run: npm run start &
    
      # Etapa 5: Verificar se o servidor está em execução
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8081

      # # Etapa 7: Executar testes Cypress manualmente
      # - name: Run Cypress tests manually
      #   run: npx cypress run --spec "cypress\e2e\taskapp"

      # # Etapa 6: Executar testes Cypress
      # - name: Run Cypress tests
      #   uses: cypress-io/github-action@v6
        # with:
        #   record: true
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        
      # Etapa 7: testes de integração
      - name: Run integration tests
        run: npm run test-api # Comando para rodar os testes no código do projeto
        
      # Etapa 8: Interrompe a execução do server
      - name: Stop server
        run: kill $(jobs -p)

  deploy:
    needs: test
    runs-on: ubuntu-latest

    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      SERVICE_ID: ${{ secrets.SERVICE_ID }}

    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":true}' \
            https://api.render.com/v1/services/$SERVICE_ID/deploys
