name: End-to-end tests
on:
  push:
    branches:
      - coisa-nova
  pull_request:
    branches:
        - main    
        - dependabot/** # Gatilho para PRs do Dependabot
  workflow_dispatch: # Permite executar o pipeline manualmente

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Etapa 3: Instalar dependências do projeto
      - name: Install dependencies
        run: npm install

        # Iniciar servidor local
      - name: Start local server
        run: npm run start &
        env:
          MONGO_URI_PROD: ${{ secrets.MONGO_URI_PROD }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: production 

        # Verificar se o servidor está em execução
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8081
            
      - name: Cypress run
        uses: cypress-io/github-action@v6