name: End-to-end tests
on:
  push:
    branches:
      - coisa-nova
  pull_request:
    branches:
        - main    
        - dependabot/** # Gatilho para PRs do Dependabot
  workflow_dispatch: # Permite executar o pipeline manualmente

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Etapa 8: Interrompe a execução do server
      - name: Stop server
        run: kill $(jobs -p)

        # Iniciar servidor local
      - name: Start local server
        run: npm run start &

        # Verificar se o servidor está em execução
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8081
            
      - name: Cypress run
        uses: cypress-io/github-action@v6